TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += measm905.db
DATA += measm905.proto

#=======================================
include $(TOP)/configure/RULES
